### ISSUE TITLE
Inefficient runtime for running images

### ISSUE THREAD

**Issue by lucbettaieb** [lucbettaieb/thesis#3]
When running a graph, the C++ code runs very slowly.  This must be due to inefficient code somewhere in the graph running area.

 - [x] Perform initial investigation
 - [x] Check for the unnecessary copying of information
 - [x] Compile for release and see if that speeds things up
---
 - [x] Determine why the Tensorflow session runs the image so slowly.

**Comment by lucbettaieb** [comment]
Copying the images, while inefficient, is not to blame for the holdup.

**Comment by lucbettaieb** [comment]
`    tensorflow::Status run_status = g_tf_session_ptr_->Run({{InputName, input_image}}, {OutputName}, {}, &finalOutput);
` is the culprit

**Comment by lucbettaieb** [comment]
Seems to be that running BIG tensors through the graph built using BIG tensors (1x307200) from a 640x480 video frame is bad.

It works, but is just slow!

I should now get reduced size training data and then use the image downsize node to run things nicely.

Also, seems as if I can't run images through the network that aren't of the same size...?

**Comment by ZhiangChen** [comment]
No, if you use the published weights of the Inception model, you can't change the size of the input image.

**Comment by ZhiangChen** [comment]
You could try tensorboard to check the running graph.

**Comment by lucbettaieb** [comment]
I'm going to test my hypothesis because I'm getting errors that seem to be indicating what I'm thinking o be correct.  After retraining the network on 640x480 images, it will error if I try to run a different size image through the graph.

**Comment by lucbettaieb** [comment]
Stopped using TF
